spring.datasource.url = jdbc:postgresql://db:5432/her
spring.datasource.username = postgres
spring.datasource.password = 24568888
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true